### ISSUE TITLE
PRACTICA6

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-mejorado-equipo_tec#1]
[Practica 6. Proceso de negocio mejorado.pdf](https://github.com/user-attachments/files/17122260/Practica.6.Proceso.de.negocio.mejorado.pdf)

**Comment by JORGELUIS2266** [comment]
de acuerdo a la rubrica obtuvieron un 20% de 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
